###
### wnc-btc-tracker config file (YAML format)
###

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:btctracker;MODE=MySQL

server:
  port: 8090

#todo: asegurar de habilitar la seguridad en profile default
security:
  basic:
    enabled: false

#default project info followed by actual injected pom-specified values.
project:
  name: wnc-btc-tracker
  version: 0.1
  description: WNC Bitcoin Tracker - Consulta precio BTC en Servicio Externo en forma recurrente y expone info estadistica via API REST
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

bitcointracker:
  fixedDelay: 10000
  url: 'https://cex.io/api/last_price/BTC/USD'
  timestampFormat: 'yyyyMMddHHmmss'

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true

spring.jpa:
    hibernate.ddl-auto: create-drop

bitcointracker:
  fixedDelay: 10000
  url: 'https://cex.io/api/last_price/BTC/USD'
  timestampFormat: 'yyyyMMddHHmmss'

#En profile test no es necesaria la seguridad
security:
  basic:
    enabled: false

logging:
  file: btc_tracker.log
  org.hibernate: INFO
